### PR TITLE
Yes mus2mid! It finally works!

### PR DESCRIPTION
**Pull request by ubunatic**

### CODE REVIEW

**Comment by tinogoehlert** [comment]
💃 😄 🔔 

awesome! YEAH

**Comment by SqiSch** [comment]
OMG!!! IT WORKS!!! GREAT WORK UWE!!!!111!!!

**Comment by fcornelius** [comment]
OMG..!!! 😭😱

**Comment by p-jahn** [comment]
💯NICE!!! 🎶👏

**Comment by jakubhuska** [comment]
😍

**Comment by 175-kavinski** [comment]
EVERYTHING IS POSSIBLE NOW!!!!!11!!1!

**Pull request merged**
